x-general: &general
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/home/user1/.Xauthority
    - QT_X11_NO_MITSHM=1
    - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user1/1000/bus
    - LIBGL_ALWAYS_INDIRECT=0
    - YARP_COLORED_OUTPUT=1
    - NVIDIA_DRIVER_CAPABILITIES=all
    - ROS_DISTRO=${ROS_DISTRO:-jazzy}
    - R1_OBR_REMOTE=${R1_OBR_REMOTE:-origin}
    - R1_OBR_BRANCH=${R1_OBR_BRANCH:-master}
    - TOUR_REMOTE=${TOUR_REMOTE:-origin}
    - TOUR_BRANCH=${TOUR_BRANCH:-master}
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "$XAUTHORITY:/home/user1/.Xauthority:ro"  # mount the auth file
    - "/etc/hosts:/etc/hosts"
    - "${HOME}/.config/yarp:/home/user1/.config/yarp"
    - "./entrypoints/entrypoint_light.sh:/home/user1/config/.entrypoint_light.sh"
    - "./entrypoints/entrypoint_heavy.sh:/home/user1/config/.entrypoint_heavy.sh"
  network_mode: host
  entrypoint: ["sh", "${ENTRY_POINT:-/home/user1/config/.entrypoint_light.sh}"]
  ipc: host
  pid: host
  privileged: true
  security_opt:
    - apparmor:unconfined
  deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

services:

# Images for the robot
  r1-object-retrieval-stable:
    image: elandini84/r1images:r1obr_cuda.${CUDA_CUSTOM:-12.1.0}_${ROS_DISTRO:-jazzy}_stable
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: elandini84/r1images:tourCore2_ubuntu24.04_${ROS_DISTRO:-jazzy}_${CUDA_CUSTOM:-12.1.0}_stable
          user_name: user1
  r1-object-retrieval-devel:
    image: elandini84/r1images:r1obr_cuda.${CUDA_CUSTOM:-12.1.0}_${ROS_DISTRO:-jazzy}_devel
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: elandini84/r1images:tourCore2_ubuntu24.04_${ROS_DISTRO:-jazzy}_${CUDA_CUSTOM:-12.1.0}_devel
          user_name: user1

# Simulation images
  r1-object-retrieval-sim-stable:
    image: elandini84/r1images:r1obr_sim_cuda.${CUDA_CUSTOM:-12.1.0}_${ROS_DISTRO:-jazzy}_stable
    build:
      context: .
      dockerfile: Dockerfile_sim
      args:
          base_img: elandini84/r1images:tourSim2_ubuntu24.04_${ROS_DISTRO:-jazzy}_${CUDA_CUSTOM:-12.1.0}_stable
          user_name: user1
  r1-object-retrieval-sim-devel:
    image: elandini84/r1images:r1obr_sim_cuda.${CUDA_CUSTOM:-12.1.0}_${ROS_DISTRO:-jazzy}_devel
    build:
      context: .
      dockerfile: Dockerfile_sim
      args:
          base_img: elandini84/r1images:tourSim2_ubuntu24.04_${ROS_DISTRO:-jazzy}_${CUDA_CUSTOM:-12.1.0}_devel
          user_name: user1

# Containers for the robot
  r1-object-retrieval-stable-container:
    image: elandini84/r1images:r1obr_cuda.${CUDA_CUSTOM:-12.1.0}_${ROS_DISTRO:-jazzy}_stable
    <<: *general
    container_name: r1-object-retrieval-stable-container
    command: terminator -g /home/user1/.config/terminator/config
  r1-object-retrieval-devel-container:
    image: elandini84/r1images:r1obr_cuda.${CUDA_CUSTOM:-12.1.0}_${ROS_DISTRO:-jazzy}_devel
    <<: *general
    container_name: r1-object-retrieval-devel-container
    command: terminator -g /home/user1/.config/terminator/config

# Containers for the simulation
  r1-object-retrieval-sim-stable-container:
    image: elandini84/r1images:r1obr_sim_cuda.${CUDA_CUSTOM:-12.1.0}_${ROS_DISTRO:-jazzy}_stable
    <<: *general
    container_name: r1-object-retrieval-sim-stable-container
    command: terminator -g /home/user1/.config/terminator/config
  r1-object-retrieval-sim-devel-container:
    image: elandini84/r1images:r1obr_sim_cuda.${CUDA_CUSTOM:-12.1.0}_${ROS_DISTRO:-jazzy}_devel
    <<: *general
    container_name: r1-object-retrieval-sim-devel-container
    command: terminator -g /home/user1/.config/terminator/config
